Feature/iosas 853
bcgov/ECC-IOSAS pull request #14
Opened 2023-07-31 17:46 UTC by mmumby

## Main Updates
- Added links to school application form labels.
- Updated required fields for school application form
- Disabled tabs until form is valid, allowing step through process for filling out the form (Note, the happy path works, ther eis a bug with raido buttons that will be addressed in a followup) 

### Additional Change
- Updated 'status' to 'iosas_reviewstatus' for eoi application payload.

2023-07-31 17:51 UTC, mmumby commented on frontend/src/utils/validation.js
> +import {
This file was just formatted

2023-08-02 16:09 UTC, fwpushan requested changes
All good check my comments for some minor feedback.

2023-08-02 16:09 UTC, fwpushan commented on frontend/src/utils/institute/formRules.js
> +    console.log(
Is this log required here?

2023-08-02 16:09 UTC, fwpushan commented on frontend/src/utils/validation.js
> +  const S1 = penDigits
Can we use a little meaningful naming here? The SonarQube basic rules set always recommend a variable name of more than three characters.

2023-08-02 16:38 UTC, mmumby commented on frontend/src/utils/validation.js
> +  const S1 = penDigits
This file was only changed for formatting - likely all of this code will be deleted as its left over from the cloned app. 
I do agree with variable names, and will ensure that any functions/variables I name will be longer and more descriptive, but I will leave this for now as its likely to be deleted when we eventually get that ticket.

2023-08-02 18:23 UTC, fwpushan approved these changes
All good

2023-08-02 18:24 UTC, merged